完善render_lexme
DragonOS-Community/Held pull request #24
Opened 2024-10-15 09:11 UTC by sparkzky

2024-10-15 15:06 UTC, GnoCiYeH requested changes

2024-10-15 15:06 UTC, GnoCiYeH commented on src/view/render/renderer.rs
> +                let prefix_len = 5;
prefix_len使用self.content_start_of_line

2024-10-15 15:06 UTC, GnoCiYeH commented on src/view/render/renderer.rs
> +                let width = tab_len - (self.screen_position.offset + 1) & tab_len;
这个地方为什么是&，没太看懂，我理解是取余吧

2024-10-15 15:06 UTC, GnoCiYeH commented on src/modules/perferences/yaml.rs
> +        4
这里不能写死，需要再default.yaml里面加一个条目：tab_width: 4

2024-10-16 01:58 UTC, sparkzky commented on src/view/render/renderer.rs
> +                let width = tab_len - (self.screen_position.offset + 1) & tab_len;
打错了哈哈

2024-10-16 14:41 UTC, GnoCiYeH approved these changes

2024-10-16 14:41 UTC, merged