normal mode
DragonOS-Community/Held pull request #28
Opened 2024-10-17 14:26 UTC by trv3wood

迁移原有Normal Mode跳转功能

2024-10-21 15:46 UTC, trv3wood commented
将带参数的命令暴露给用户，限于default.yaml的解析和cmd_map的生成方式，仅支持 `number + single_char`形式的命令自定义
```yaml
  shift-L: cursor::move_to_end_of_line
  shift-H: cursor::move_to_start_of_line
  shift-T: monitor::scroll_to_first_line
  shift-B: monitor::scroll_to_last_line
  shift-G: normal::move_to_target_line # n + G 移动到第 n 行
  j: normal::move_down_n # n + j 向下移动 n 行
  k: normal::move_up_n # 同理以下
  h: normal::move_left_n
  l: normal::move_right_n
  d: 
    - normal::transition
    - normal::delete_some
  _: normal::transition
```

2024-10-27 11:08 UTC, trv3wood commented
按d进入专门的Delete Mode
- w: 删除单词
- d: 删除行

2024-11-02 08:52 UTC, GnoCiYeH requested changes

2024-11-02 08:52 UTC, GnoCiYeH commented on src/application/mode/normal.rs
> +pub fn exec_j_cmd(app: &mut Application) {
这种函数的命名不规范，函数名应该体现函数作用

2024-11-02 08:52 UTC, GnoCiYeH commented on src/application/handler/normal.rs
> +        let count = CMD_COUNTER.read().unwrap().clone();
CMD_COUNTER作为Application的成员变量吧，因为全局的Application就是一个单例，没必要再搞一个全局变量

2024-11-02 09:29 UTC, trv3wood commented on src/application/mode/normal.rs
> +pub fn exec_j_cmd(app: &mut Application) {
> 这种函数的命名不规范，函数名应该体现函数作用

已经改为move_down_n

2024-11-09 03:14 UTC, merged