Zys patch
DragonOS-Community/Held pull request #6
Opened 2024-07-20 07:41 UTC by trv3wood

实现了一系列与Vim类似的功能：
- hjkl上下左右移动光标
- '0'与'$'行首行末跳转
- ‘w'与'e'单词跳转
- 'dd'删除行等
- 'x'删除字符

2024-07-21 06:53 UTC, trv3wood commented
添加'b'跳转至前一单词，'dw'删除单词的功能

2024-07-21 07:06 UTC, GnoCiYeH requested changes

2024-07-21 07:06 UTC, GnoCiYeH commented on src/utils/buffer.rs
> +    pub fn search_nextw_beg(&self, x: u16, y: u16) -> usize {
命名写全会更好，这里的beg最好写全begin

2024-07-21 07:06 UTC, GnoCiYeH commented on src/utils/buffer.rs
> +    pub fn search_prevw_beg(&self, x: u16, y: u16) -> Option<usize> {
同理

2024-07-21 07:06 UTC, GnoCiYeH commented on src/utils/ui/mode/mode.rs
> +        if x as usize >= linesize - 2 {
这种减2的操作，这个2代表什么，应该尽量避免这种魔数

2024-07-25 09:28 UTC, GnoCiYeH approved these changes

2024-07-25 09:29 UTC, merged